import Head from 'next/head'
import { useSession} from "next-auth/react";
import useUserInfo from '../hooks/useUserInfo';
import UsernameForm from '../components/UsernameForm';


export default function Home() {

 
  const {userInfo, status: userInfoStatus } = useUserInfo()

  

  

  if( userInfoStatus === 'loading') {
    return 'loading user info'  
  }

  if( !userInfo?.username) {
    return <UsernameForm />
  }

  return (
    <div >
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>
        <h1 className='text-3xl'>
          Welcome to Twitter. Logged in as {userInfo.username}
        </h1>

       
      </main>

      
    </div>
  )
}
